[Interface]
PrivateKey = EGBCEhWrE2LpK39HJgEYo0yV0nKyy000nDs4hPNOklA=
Address = 10.100.10.4/32
DNS = 10.10.10.254

[Peer]
PublicKey = qE8kYQ6pd35CFjaaf8BbKyFdkJIhlX5N0x7WmOqivkU=
PresharedKey = 3wm09Bl2xTSxXWOy4ITDaUeV2Ffnuoh96pZhbu3iu+U=
Endpoint = vpn.qf0xb.de:51820
AllowedIPs = 10.10.10.0/24
