rp: ENC[AES256_GCM,data:S7YH9vOdBHTk/R9L+cdD+wtORzGW2Yr+MROCwOIinh5t1yUiR2qEptbUiYqD/zZTw91QesHLlzgnzyIEoCxMUypJBV+vS34eX1At6rIPkRnSWCCUdyrqMaWloKAo7Kusv5gm9y58v6RzXg==,iv:aQReHDeTEr3m96OYARovVV1M1NPgP+rNAiq933syGbk=,tag:TcnOyQGMlk4ag9htglujRw==,type:str]
up: ENC[AES256_GCM,data:g5KY7PBGIQariWD7fo7K5c0WZv58uK+Ft7MU0xeIEuvJ7kMIIHxetBwUlU4qOs976Uq91ZfM3oN0qpfzC7jZ8DvTzGrirLyOILmBIYN2cLBPGWQb2q+KmjsILFhiJJCSwQoCDU10JUWuKA==,iv:XltAR6kyG3OMemJ9iCQhl6M5vVJuKf+JsztS7/0olHQ=,tag:co2A9ObYE3MjlokQqF2qrg==,type:str]
github_token: ENC[AES256_GCM,data:mOKhXhyrlNiLp0gNfjfr/AYtMk97qCc+SIUqopHoCNc1ucDSwuBLKG3ohHdPUAUiQrh8rjHlo8/+50kErJBptQYlwntxHa1vzQV/tG58JbwFmklNjes4K6fVJnlf,iv:z+JFPSxDQR+4xTi0aom8YxUkolUB/I63bGHizeglhUg=,tag:v1w1sPDL1hogWanPOoNMFQ==,type:str]
borgbackup-eu-passphrase: ENC[AES256_GCM,data:I2ZoqIU8RwwJ8cK/O9WNkZuRJcpVLbiBmcrHjpT+6pba8anFGMwJ9SKEy7Gy/X/Ib6TXomrDsduEY5TyoxWjAljgtENZVZHd8ddpRwLQdJBDss94MR2+fcwRfACKze3tJ01YoBiSUM4l4TTUw0G+5+cVnjZb60u5rgnck9CCp4s=,iv:ous+N+Sa79+MvhGeSti1hgdh+cYkJJjfaNq+lZPAa/M=,tag:4Ywk3oMVBjccilDNevmuLA==,type:str]
borgbackup-us-passphrase: ENC[AES256_GCM,data:j79qes+FJJL8dkoe7EHXCIXB5FO5yG6w2ISk1aqn2I/zrFM+0qFTDG/cNm0rv1rpI5HmZe7qiEASuAYzVIjEIWUDisnR0Xddq7C29Opu9bcwyNscLkbYwxG5lOyeGb2FKKPFzWjHcTS67B9VCYbkuo/ex5bWJYf0s3eAnk0s98s=,iv:Tun4Sr6GhTntuoS1tLlQwr4wBT7jyzqbSUyVTm8gNxk=,tag:LoMYJsOb+hzCyJJ9RsxgZg==,type:str]
garnix:
    netrc: ENC[AES256_GCM,data:D9Osmm8eaT2DWfD0Wf0yGrVXJ8jsipaGeUz/jDqzelbQjVll7XOKNEz/MrAlMqDut8nI1QBLIkeyIMJds4c84prAMbkglIQiPpFyrZEhBGyuD2ENcYM6dVmB,iv:pjybrE9usPAft781uAAzA5pY+0ntFHeH/iVeVHL6S/c=,tag:FUHzRWAk+uFMI4fy1WZSFw==,type:str]
sops:
    age:
        - recipient: age1wxzqt7l9v4w7sm5lpe9qj8v9cw3e0w35zg6c6tdmns264l0urs4q8m2x3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSVpkeURiT0g5MnNNaCtr
            aER1NnRPOEpLY3ptQUlOZmRDWUNHOE1zajJRClJuZ2l5QXN6T2orYVVqd3RFYzQy
            Qkp6YXZRZ0FBeFNlOWpDTDFvRGZTT2sKLS0tIHVKNDRvTkdEQksyb2h4ZXlGcGk4
            d01TV0Z5L0JGbTN4R3loZGN4QkZJS2cKCXNJfDJWTgoT3g9WBQw2IF7yQnCMnE6v
            PeVJE48iMTCBJtlVv0oxncttrdgipo/a9M6CMY6tf6PZMjZdRjf5dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T01:24:49Z"
    mac: ENC[AES256_GCM,data:+qDGLII7wEemhRudAbefxs3pg2/RdJyDEc6EPYl4mmt2TNkC1wgtVciacXDKAyVjXLG3NNChiXyfehfXVXWbHUs2dFWwHD0UIUEYD+sSPRP/cQjMN/seJnn+Rv92RFsBrZ0Ge6e5SFrLC4E2xznnX0M7qknlnxbkFuZCRpLOJjE=,iv:/WuzkUBlHrEztdZObe82abbKW0aPvA5IeoSTBoCSj2o=,tag:YiMnoRkIGs17+9xmFxNkTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
